export const defaultDemoData = {
  packages: [
    {
      id: "pkg-balagha",
      slug: "باقة-البلاغة-العربية",
      title: "باقة البلاغة العربية",
      description: "مسار تطبيقي في البيان والبديع والمعاني مع تحليل نصوص أدبية.",
      categoryId: "cat-balagha",
      teacherId: "teacher-2",
      coverImage: "placeholder-balagha",
      isPublished: true,
      isFeatured: true,
      priceType: "free",
      priceMad: 0,
      lessonsCount: 4,
      order: 1,
      academicLevel: "الرابعة متوسط",
    },
    {
      id: "pkg-jahili",
      slug: "باقة-الأدب-الجاهلي",
      title: "باقة الأدب الجاهلي",
      description: "قراءة خصائص الأدب الجاهلي ودراسة نماذج الشعر والنصوص المؤسسة.",
      categoryId: "cat-old-literature",
      teacherId: "teacher-1",
      coverImage: "placeholder-jahili",
      isPublished: true,
      isFeatured: true,
      priceType: "paid",
      priceMad: 499,
      lessonsCount: 4,
      order: 2,
      academicLevel: "الثالثة متوسط",
    },
    {
      id: "pkg-naqd",
      slug: "باقة-النقد-الأدبي",
      title: "باقة النقد الأدبي",
      description: "مناهج النقد الأدبي القديمة والحديثة مع نماذج تحليل معمقة.",
      categoryId: "cat-naqd",
      teacherId: "teacher-3",
      coverImage: "placeholder-naqd",
      isPublished: false,
      isFeatured: false,
      priceType: "paid",
      priceMad: 349,
      lessonsCount: 3,
      order: 3,
      academicLevel: "الأولى ثانوي",
    },
    {
      id: "pkg-texts",
      slug: "باقة-تحليل-النصوص",
      title: "باقة تحليل النصوص الأدبية",
      description: "منهجية القراءة والتحليل الأدبي للنصوص الشعرية والنثرية.",
      categoryId: "cat-text-analysis",
      teacherId: "teacher-2",
      coverImage: "placeholder-texts",
      isPublished: true,
      isFeatured: false,
      priceType: "free",
      priceMad: 0,
      lessonsCount: 2,
      order: 4,
      academicLevel: "الثانية ثانوي",
    },
  ],
  lessons: [
    {
      id: "lesson-b-1",
      slug: "الصورة-البيانية",
      title: "الصورة البيانية",
      description: "مدخل إلى التشبيه والاستعارة والكناية مع أمثلة تطبيقية من الشعر العربي.",
      packageId: "pkg-balagha",
      type: "video",
      duration: 28,
      isPublished: true,
      accessType: "free",
      order: 1,
      youtubeUrl: "https://www.youtube.com/watch?v=Hf4_Ma5t8xE",
      attachments: ["ملف-تحليل-بلاغي.pdf"],
    },
    {
      id: "lesson-b-2",
      slug: "الاستعارة",
      title: "الاستعارة",
      description: "شرح أنواع الاستعارة ووظائفها الجمالية في بناء الصورة الأدبية.",
      packageId: "pkg-balagha",
      type: "video",
      duration: 24,
      isPublished: true,
      accessType: "premium",
      order: 2,
      youtubeUrl: "https://youtu.be/Hf4_Ma5t8xE",
      attachments: [],
    },
    {
      id: "lesson-j-1",
      slug: "خصائص-الشعر-الجاهلي",
      title: "خصائص الشعر الجاهلي",
      description: "تحليل البناء الفني للقصيدة الجاهلية وسياقاتها التاريخية.",
      packageId: "pkg-jahili",
      type: "text",
      duration: 30,
      isPublished: true,
      accessType: "free",
      order: 1,
      youtubeUrl: "https://www.youtube.com/watch?v=8YzabSdk7ZA",
      attachments: ["نصوص-جاهلية-مختارة.pdf"],
    },
    {
      id: "lesson-j-2",
      slug: "المعلقات",
      title: "المعلقات",
      description: "قراءة بلاغية ونقدية لنماذج مختارة من المعلقات.",
      packageId: "pkg-jahili",
      type: "video",
      duration: 35,
      isPublished: true,
      accessType: "premium",
      order: 2,
      youtubeUrl: "",
      attachments: [],
    },
  ],
  categories: [
    { id: "cat-nahw", name: "النحو", slug: "النحو", description: "قواعد اللغة العربية وبناء الجملة.", active: true },
    { id: "cat-balagha", name: "البلاغة", slug: "البلاغة", description: "البيان والبديع والمعاني.", active: true },
    { id: "cat-sher", name: "الشعر", slug: "الشعر", description: "فنون الشعر العربي وتطبيقاته.", active: true },
    { id: "cat-naqd", name: "النقد", slug: "النقد", description: "مناهج النقد الأدبي وتحليل النصوص.", active: true },
    { id: "cat-old-literature", name: "الأدب القديم", slug: "الأدب-القديم", description: "الأدب الجاهلي والأموي والعباسي.", active: true },
    { id: "cat-modern-literature", name: "الأدب الحديث", slug: "الأدب-الحديث", description: "الاتجاهات الحديثة في الأدب العربي.", active: true },
    { id: "cat-text-analysis", name: "تحليل النصوص", slug: "تحليل-النصوص", description: "قراءة النص الأدبي وتحليله.", active: true },
    { id: "cat-arud", name: "العروض", slug: "العروض", description: "الأوزان والقوافي والبحور الشعرية.", active: true },
  ],
  plans: [
    { id: "plan-m", name: "باقة شهرية", period: "شهري", price: "199 دج", featured: false, active: true, features: ["دروس مباشرة", "ملفات تحليل"] },
    { id: "plan-q", name: "باقة فصلية", period: "فصلي", price: "549 دج", featured: true, active: true, features: ["متابعة أكاديمية", "اختبارات دورية"] },
    { id: "plan-y", name: "باقة سنوية", period: "سنوي", price: "1,999 دج", featured: false, active: true, features: ["وصول كامل", "جلسات مراجعة"] },
  ],
  homepageContent: {
    heroTitle: "تعلّم الأدب العربي بمنهجية واضحة",
    heroSubtitle: "منصة متخصصة في الأدب العربي وعلومه",
    ctaTitle: "جاهز لتوسيع أفقك الأدبي؟",
    ctaSubtitle: "دروس مباشرة، شروحات مركزة، وتمارين تحليلية.",
    featuredHeading: "المسارات المميزة",
    supportText: "للاستفسار الأكاديمي: contact@maerifah.app",
    footerText: "صُممت لخدمة الدرس الأدبي العربي.",
  },
  ctaButtons: [
    { id: "btn-1", label: "إنشاء حساب", route: "/register", visible: true, variant: "primary", placement: "homepage" },
    { id: "btn-2", label: "تسجيل الدخول", route: "/login", visible: true, variant: "secondary", placement: "homepage" },
    { id: "btn-3", label: "تصفح الباقات", route: "/packages", visible: true, variant: "secondary", placement: "homepage" },
    { id: "btn-4", label: "متابعة التعلم", route: "/packages", visible: true, variant: "secondary", placement: "dashboard" },
  ],
  announcements: [
    { id: "ann-1", title: "تم فتح التسجيل في مسار البلاغة العربية", type: "info", placement: "homepage" },
    { id: "ann-2", title: "موعد اختبار النقد الأدبي الأسبوع القادم", type: "warning", placement: "dashboard" },
  ],
  teachers: [
    { id: "teacher-1", name: "الدكتور عبد الرحمن السالمي", specialization: "الأدب القديم", active: true, assignedPackageIds: ["pkg-jahili"] },
    { id: "teacher-2", name: "الدكتورة مريم حداد", specialization: "البلاغة وتحليل النصوص", active: true, assignedPackageIds: ["pkg-balagha", "pkg-texts"] },
    { id: "teacher-3", name: "الدكتور نزار العلواني", specialization: "النقد الأدبي", active: false, assignedPackageIds: ["pkg-naqd"] },
  ],
  students: [
    {
      id: "st-1",
      name: "محمد الأندلسي",
      email: "mohamed@example.com",
      currentPlan: "باقة فصلية",
      enrolledCoursesCount: 4,
      progress: 63,
      accountStatus: "نشط",
      walletBalance: 2000,
    },
    {
      id: "st-2",
      name: "ليلى الشامسي",
      email: "layla@example.com",
      currentPlan: "باقة شهرية",
      enrolledCoursesCount: 2,
      progress: 35,
      accountStatus: "نشط",
      walletBalance: 0,
    },
  ],
  rechargeRequests: [],
  walletTransactions: [],
  enrollments: [],
  settings: {
    platformName: "منصة ينفع",
    supportEmail: "contact@maerifah.app",
    footerText: "صُممت لخدمة الدرس الأدبي العربي.",
    socialFacebook: "",
    socialYouTube: "",
    demoMode: true,
    maintenanceMode: false,
    maintenanceBanner: "لا توجد صيانة حالية",
  },
};
